version: 2.1

jobs:
  docker-nightly:
    docker:
      - image: docker:20.10.14-git
    steps:
      - run:
          name: login to quay.io
          command: docker login --username="${QUAY_USER}" --password="${QUAY_PASS}" quay.io
      - run:
          name: clone influxdata/influxdata-docker
          command: git clone https://github.com/influxdata/influxdata-docker
      - run:
          name: build and push telegraf:nightly
          command: |
            cd influxdata-docker/telegraf/nightly
            docker build -t telegraf .
            docker tag telegraf quay.io/influxdb/telegraf:nightly
            docker image ls
            docker push quay.io/influxdb/telegraf:nightly
      - run:
          name: build and push telegraf:nightly-alpine
          command: |
            cd influxdata-docker/telegraf/nightly/alpine
            docker build -t telegraf-alpine .
            docker tag telegraf-alpine quay.io/influxdb/telegraf:nightly-alpine
            docker image ls
            docker push quay.io/influxdb/telegraf:nightly-alpine

workflows:
  version: 2
  check:
    jobs:
      - docker-nightly
