style: github
template: CHANGELOG.go.tmpl
info:
  title: CHANGELOG
  repository_url: https://github.com/influxdata/telegraf
options:
  tag_filter_pattern: '^v((([0-9]+)\.([0-9]+)\.([0-9]+))?)$'
  commits:
    filters:
      Type:
        - feat
        - fix
  commit_groups:
    # title_maps:
    #   feat: Features
    #   fix: Bug Fixes
    #   perf: Performance Improvements
    #   refactor: Code Refactoring
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
