name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # Trigger every day at 16:00 UTC
    - cron:  '0 16 * * *'
jobs:
  golangci-pr:
    if: github.ref != 'refs/heads/master'
    strategy:
      matrix:
        go-version: [1.17.7]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: lint-pr-changes
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          only-new-issues: true
  golangci-master:
    if: github.ref == 'refs/heads/master'
    name: lint-master-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          only-new-issues: true
          args: --issues-exit-code=0
